# Site Settings
title: First Ward Civic Club - Houston
email: fwcc2020@gmail.com
description: >
  First Ward Civic Club
baseurl: "/1stward"
url: "http://crocken.github.io"
twitter_username: 
github_username:  
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
